spring: 
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#Eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: INFO